# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INFO_BOOK', '0003_auto_20170530_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=250),
        ),
    ]
