# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('INFO_BOOK', '0004_auto_20170530_1647'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
